name: Run Unit Tests

on:
  workflow_call:
    outputs:
      coverage_artifact_url:
        description: 'url of coverage artifact'
        value: ${{ jobs.unit-tests.outputs.artifact-url }}
  push:
    branches:
      - 'main'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    outputs:
      artifact-url: ${{ steps.artifact_upload.outputs.artifact-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load environment
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/development.env

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Unit Tests
        working-directory: .
        run: make test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        id: artifact_upload
        with:
          name: code-coverage
          path: coverage.*
